const PURCHASE_NAMESPACE = 'Purchase';
const CATEGORY_NAMESPACE = 'Category';
const COMPANY_NAMESPACE = 'Company';
const ITEM_NAMESPACE = 'Item';
const AUTH_NAMESPACE = 'Auth';
const MACHINE_NAMESPACE = 'Machine';
const WAYBILL_NAMESPACE = 'Waybill';
const DISTRIBUTION_NAMESPACE = 'Distribution';
const WORKER_NAMESPACE = 'Worker';
const REPAIR_ITEM_NAMESPACE = 'RepairItem';
const UPLOADER_NAMESPACE = 'Uploader';

export {
  PURCHASE_NAMESPACE,
  CATEGORY_NAMESPACE,
  COMPANY_NAMESPACE,
  ITEM_NAMESPACE,
  AUTH_NAMESPACE,
  MACHINE_NAMESPACE,
  WAYBILL_NAMESPACE,
  DISTRIBUTION_NAMESPACE,
  WORKER_NAMESPACE,
  REPAIR_ITEM_NAMESPACE,
  UPLOADER_NAMESPACE,
};
