const PURCHASE_NAMESPACE = 'Purchase';
const CATEGORY_NAMESPACE = 'Category';
const COMPANY_NAMESPACE = 'Company';
const ITEM_NAMESPACE = 'Item';
const AUTH_NAMESPACE = 'Auth';

export {
  PURCHASE_NAMESPACE,
  CATEGORY_NAMESPACE,
  COMPANY_NAMESPACE,
  ITEM_NAMESPACE,
  AUTH_NAMESPACE,
};
